#ifdef GLOBALVARIABLEINITIALIZEORDERDLL_EXPORTS
#define GLOBALVARIABLEINITIALIZEORDERDLL_API extern "C" __declspec(dllexport)
#else
#define GLOBALVARIABLEINITIALIZEORDERDLL_API extern "C" __declspec(dllimport)
#endif

GLOBALVARIABLEINITIALIZEORDERDLL_API int GetCallCount(void);